"""Multi-turn VERL AgentLoop backed by the official AgentDojo environment."""

from __future__ import annotations

import json
from typing import Any

from agentdojo.functions_runtime import FunctionsRuntime
from agentdojo.task_suite.load_suites import get_suite
from agentdojo.types import text_content_block_from_string
from verl.experimental.agent_loop.tool_agent_loop import AgentState, ToolAgentLoop

from verl_training.state import STATE_KEY, AgentDojoTrajectoryState


def _tool_call_format_is_valid(raw_output: str, parsed_tool_call_count: int) -> bool:
    """Return whether every emitted Hermes tool-call block parsed successfully."""
    start_count = raw_output.count("<tool_call>")
    end_count = raw_output.count("</tool_call>")
    if start_count == 0 and end_count == 0:
        return True
    return start_count == end_count == parsed_tool_call_count


class AgentDojoAgentLoop(ToolAgentLoop):
    """Run a full AgentDojo task and expose official checker results to reward workers."""

    async def run(self, sampling_params: dict[str, Any], **kwargs: Any):
        extra_info = kwargs.get("extra_info", {}) or {}
        case_json = extra_info.get("agentdojo_case_json")
        if not case_json:
            raise ValueError("extra_info.agentdojo_case_json is required")
        self._agentdojo_case = json.loads(case_json) if isinstance(case_json, str) else dict(case_json)

        output = await super().run(sampling_params, **kwargs)
        # The initial colocated vLLM rollout has not gone through a weight-update
        # call yet, so VERL may return None for its model-version fields. The
        # trajectory was generated by the current dataloader step in that case.
        raw_step = kwargs.get("global_steps", 0)
        current_step = int(raw_step if raw_step is not None else 0)
        for key in ("global_steps", "min_global_steps", "max_global_steps"):
            if output.extra_fields.get(key) is None:
                output.extra_fields[key] = current_step

        state = output.extra_fields.pop(STATE_KEY, None)
        if not isinstance(state, AgentDojoTrajectoryState):
            output.extra_fields["agentdojo_result"] = {
                "valid": False,
                "error": "AgentDojo trajectory state was missing",
            }
            return output

        try:
            model_output = [text_content_block_from_string(state.final_model_output)]
            utility = state.suite._check_user_task_utility(
                state.user_task,
                model_output,
                state.pre_environment,
                state.environment,
                state.function_calls,
            )
            if state.injection_task is None:
                attack_success = False
                safety = True
                safety_applicable = False
            else:
                attack_success = state.suite._check_injection_task_security(
                    state.injection_task,
                    model_output,
                    state.pre_environment,
                    state.environment,
                    state.function_calls,
                )
                safety = not attack_success
                safety_applicable = True
            output.extra_fields["agentdojo_result"] = {
                "valid": True,
                "case_id": self._agentdojo_case["case_id"],
                "case_type": self._agentdojo_case["case_type"],
                "utility": bool(utility),
                "safety": bool(safety),
                "safety_applicable": bool(safety_applicable),
                "attack_success": bool(attack_success),
                "num_tool_calls": len(state.function_calls),
                "format_valid": bool(state.format_valid),
            }
        except Exception as exc:
            output.extra_fields["agentdojo_result"] = {
                "valid": False,
                "case_id": self._agentdojo_case.get("case_id"),
                "error": f"{type(exc).__name__}: {exc}"[:2000],
            }
        return output

    async def _handle_pending_state(self, agent_data, sampling_params):
        case = self._agentdojo_case
        suite = get_suite(case["benchmark_version"], case["suite"])
        injections = case.get("injections") or {}
        environment = suite.load_and_inject_default_environment(injections)
        user_task = suite.get_user_task_by_id(case["user_task_id"])
        environment = user_task.init_environment(environment)
        pre_environment = environment.model_copy(deep=True)
        injection_task_id = case.get("injection_task_id")
        injection_task = suite.get_injection_task_by_id(injection_task_id) if injection_task_id else None
        agent_data.extra_fields[STATE_KEY] = AgentDojoTrajectoryState(
            suite=suite,
            user_task=user_task,
            injection_task=injection_task,
            runtime=FunctionsRuntime(suite.tools),
            pre_environment=pre_environment,
            environment=environment,
        )
        return await super()._handle_pending_state(agent_data, sampling_params)

    async def _handle_generating_state(
        self,
        agent_data,
        sampling_params: dict[str, Any],
        ignore_termination: bool = False,
    ) -> AgentState:
        next_state = await super()._handle_generating_state(
            agent_data,
            sampling_params,
            ignore_termination=ignore_termination,
        )
        state = agent_data.extra_fields.get(STATE_KEY)
        if isinstance(state, AgentDojoTrajectoryState) and agent_data.messages:
            last_message = agent_data.messages[-1]
            if last_message.get("role") == "assistant":
                raw_output = self.tokenizer.decode(agent_data.response_ids)
                state.format_valid = state.format_valid and _tool_call_format_is_valid(
                    raw_output,
                    len(agent_data.tool_calls),
                )
                state.final_model_output = str(last_message.get("content") or "")
            else:
                # ToolAgentLoop checks turn/token limits before appending the
                # latest assistant message. Preserve that final generation for
                # output-sensitive official checkers when a limit is hit.
                state.final_model_output = self.tokenizer.decode(
                    agent_data.response_ids,
                    skip_special_tokens=True,
                )
        return next_state
